version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-myPass}
      POSTGRES_USER: ${POSTGRES_USER:-nantedevy}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 1025 --hide-extensions STARTTLS
    restart: always
    ports:
        - 8081:80

  app:
    image: agence-immo-site-sf:latest
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL postgres://${POSTGRES_USER:-nantedevy}:${POSTGRES_PASSWORD:-myPass}@docker-database-1:5432/${POSTGRES_DB:-app}
    volumes:
      - D:/DEV/Application/agence_immo_site_sf:/var/www

volumes:
  db-data:
